services:
    frontphp:
        build:
            context: native_php_parser
            dockerfile: Dockerfile
        ports:
            - 5000:5000
    parser:
        build:
            context: dhscanner_ast_parser
            dockerfile: Dockerfile
        ports:
            - 3000:3000
